# Generated by Django 5.2 on 2025-04-09 17:31

import django.db.models.deletion
from django.db import migrations, models


def create_default_books(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Book.objects.create(title='The Power of Habit', author='Charles Duhigg', genre='Personal Development', published_year=2012)
    Book.objects.create(title="Life's Amazing Secrets", author='Gaur Gopal Das', genre='Self Help', published_year=2018)
    Book.objects.create(title="How to Win Friends & Influence People", author='Dale Carnegie', genre='Communication', published_year=1998)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
            ],
        ),
        migrations.RunPython(create_default_books),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
            ],
        ),
    ]
